server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${postgre}
    url: jdbc:postgresql://localhost:5432/hrms_authservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}


rabbitmq:
  authExchange: authExchange
  register-visitor-queue: registerVisitorQueue
  register-visitor-bindingKey: registerVisitorBindingKey
  register-manager-queue: registerManagerQueue
  register-manager-bindingKey: registerManagerBindingKey
  activation-mail-queue: activationMailQueue
  activation-mail-bindingKey: activationMailBindingKey
  register-employee-mail-queue: registerEmployeeMailQueue
  register-employee-bindingKey: registerEmployeeBindingKey
  save-employee-queue: saveEmployeeQueue
  save-employee-bindingKey: saveEmployeeBindingKey
  activate-status-queue: activateStatusQueue
  activate-status-bindingKey: activateStatusBindingKey
  update-user-queue: updateUserQueue
  delete-user-by-authid-queue: deleteUserByAuthidQueue
  create-company-queue: createCompanyQueue
  create-company-bindingKey: createCompanyBindingKey
  create-admin-user-queue: createAdminUserQueue
  create-admin-user-bindingKey: createAdminUserBindingKey
  activate-manager-status-queue: activateManagerStatusQueue