server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${postgre}
    url: jdbc:postgresql://localhost:5432/hrms_userservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user


jwt:
  secretKey: ${java9secretkey}
  issuer: ${java9issuer}
  audience: ${java9audience}


rabbitmq:
  userExchange: userExchange
  register-visitor-queue: registerVisitorQueue
  register-manager-queue: registerManagerQueue
  save-employee-queue: saveEmployeeQueue
  activate-status-queue: activateStatusQueue
  update-user-queue: updateUserQueue
  update-user-bindingKey: updateUserBindingKey
  delete-user-by-authid-bindingKey: deleteUserByAuthidBindingKey
  delete-user-by-authid-queue: deleteUserByAuthidQueue
  delete-auth-by-id-queue: deleteAuthByIdQueue
  approve-manager-mail-queue: approveManagerMailQueue
  approve-manager-mail-bindingKey: approveManagerMailBindingKey
  create-admin-user-queue: createAdminUserQueue
  activate-manager-status-bindingKey: activateManagerStatusBindingKey
  activate-manager-status-queue: activateManagerStatusQueue
  delete-users-contains-companyName-queue: deleteUsersContainsCompanyNameQueue
  delete-auth-contains-companyName-queue: deleteAuthContainsCompanyNameQueue
  delete-auth-contains-companyName-bindingKey: deleteAuthContainsCompanyNameBindingKey
  update-users-companyName-details-queue: updateUsersCompanyNameDetailsQueue
  delete-company-by-register-deny-Queue: deleteCompanyByRegisterDenyQueue
  delete-company-by-register-deny-bindingKey: deleteCompanyByRegisterDenyBindingKey
  manager-deny-mail-bindingKey: managerDenyMailBindingKey
  manager-deny-mail-queue: managerDenyMailQueue


